# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CalLatLong
                                 A QGIS plugin
 Permite convertr G,M,S y grados decimales
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-04-25
        copyright            : (C) 2022 by Raul Lanza
        email                : rlanzaf@unah.hn
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CalLatLong class from file CalLatLong.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .CalLatLong import CalLatLong
    return CalLatLong(iface)
