# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CalLatLongDialog
                                 A QGIS plugin
 Permite convertr G,M,S y grados decimales
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-04-25
        git sha              : $Format:%H$
        copyright            : (C) 2022 by Raul Lanza
        email                : rlanzaf@unah.hn
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'CalLatLong_dialog_base.ui'))


class CalLatLongDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(CalLatLongDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        
        #disparadores de latitud
        self.spbLatG.valueChanged.connect(self.latDMStoDD)
        self.spbLatM.valueChanged.connect(self.latDMStoDD)
        self.spbLatS.valueChanged.connect(self.latDMStoDD)
        self.cmbLatH.currentTextChanged.connect(self.latDMStoDD)
        
        #Disparador para grados decimales
        self.spbLatGD.editingFinished.connect (self.latDDtoDMS)
        
    def latDMStoDD(self):
        ideg = self.spbLatG.value()
        imin = self.spbLatM.value()
        dseg = self.spbLatS.value()
        sHem = self.cmbLatH.currentText()
        
        dDD = float(ideg) + imin/60 + dseg/3600
        
        if sHem == 'S':
            dDD = dDD * -1
        
        self.spbLatGD.setValue(dDD)
        
    def latDDtoDMS(self):
        dDD = self.spbLatGD.value()
        
        ideg = int(dDD)
        dMin = (dDD - ideg) * 60
        imin = int(dMin)
        dseg = (dMin - imin) * 60
        
        self.spbLatG.setValue(abs(ideg))
        self.spbLatM.setValue(abs(imin))
        self.spbLatS.setValue(abs(dseg))
        
        if dDD < 0:
            self.cmbLatH.setCurrentText("S")
        else:
            self.cmbLatH.setCurrentText("N")
            
    #disparadores de longitud
        self.spbLonG.valueChanged.connect(self.lonDMStoDD)
        self.spbLonM.valueChanged.connect(self.lonDMStoDD)
        self.spbLonS.valueChanged.connect(self.lonDMStoDD)
        self.cmbLonH.currentTextChanged.connect(self.lonDMStoDD)
        
        #Disparador para grados decimales
        self.spbLonGD.editingFinished.connect (self.lonDDtoDMS)
       
    def lonDMStoDD(self):
        ideg = self.spbLonG.value()
        imin = self.spbLonM.value()
        dseg = self.spbLonS.value()
        sHem = self.cmbLonH.currentText()
        
        dDD = float(ideg) + imin/60 + dseg/3600
        
        if sHem == 'W':
            dDD = dDD * -1
        
        self.spbLonGD.setValue(dDD)
        
    def lonDDtoDMS(self):
        dDD = self.spbLonGD.value()
        
        ideg = int(dDD)
        dMin = (dDD - ideg) * 60
        imin = int(dMin)
        dseg = (dMin - imin) * 60
        
        self.spbLonG.setValue(abs(ideg))
        self.spbLonM.setValue(abs(imin))
        self.spbLonS.setValue(abs(dseg))
        
        if dDD < 0:
            self.cmbLonH.setCurrentText("W")
        else:
            self.cmbLonH.setCurrentText("E")